Default: &defaults
  database: Nicomail.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: Nicomail_test.sqlite3
  <<: *defaults

Staging:
  database: Nicomail_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: Nicomail_production.sqlite3
  poolsize: 100
  <<: *defaults
